language: python
python:
  - "3.7.2"
  - "3.6"

# Linux distribution
dist: xenial

# Superuser
sudo: yes

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run  tests
script: python manage.py test

after_success:
  - coveralls
