language: python
python:
  - "3.7.2"

# Linux distribution
dist: xenial

# Superuser
sudo: yes

# command to install dependencies
install:
  - pip install -r requirements.txt

# commando to run  tests
script: python manage.py test
